language: node_js
node_js: node
services:
    - mongodb
deploy: 
  provider: heroku
  edge: true
  api_key:
    secure: Gyt+yjmJcbPilbwmjO+NlIeD3Xgv+h91zcDuFUGtTmte3zNX6wah6i5MdpPGatznS6nIfzp0NkZ5cnq5RylMV5kXT5jsL/edSsIYbC1cTDWsAAFwNaRNas6YRRpRDovSPSjdCoTeV9asmI6qioryGoGMXN3CmFGCU3P2dxPDIvA5qMiDBLRt2QYPrd2Ey7M29cHPKHzbJ9B6aLBPoieV+2HEb5KqHpnv2v+4BK8dDe4eE63mQ7qfcy90e8H579/ILoU/zeX4kE8lcfEOpXcW0cJCCzJyG+Cxs3n6CXn8g8VKrVJRuaTiJNM/xleUERlG+eaFj/eig/tDe9Eo4WRdW6jrmmTF9jl4imGVTDCOPXPeF6B9B3XGqZWfjkFh1apoROs+p3JvInyL+93MUD8YZbuWRfKVa1ypI19Qxm6CAxAfyhv+GlAh4gTc/6uy5YW8wpmpcn0PgCyODGy0N7EWySMJlguEJ5ri5p5xLy6DOmeAvrJkR89TzJTN+DB4PpPV4O1VWM+Br+3SRnC/txeQ7BRpl0F+2xRo2RLWb9h5AcUh4mlMhjB7N2S1ilZ0wn6gA39OIvKhcnR4w9XeuQM6Qpwxy5qXR/bZ2Leq8LwP/P8npysUzjuj0GtHpUcR4KxOmqqlKUmehkmARfpDQDCd1A4tqMcfX3fu7jHefJYMK10=
  app: arcane-mountain-22452
  on:
    repo: cymruhangu/caprese-app-back
